import { Modal, Navbar } from "@/components/ui";
import "./globals.css";
import RegisterModal from "@/components/ui/Modal/RegisterModal";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Airbnb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <RegisterModal />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
