import { Navbar } from "@/components/ui";
import "./globals.css";
import RegisterModal from "@/components/ui/Modal/RegisterModal";
import { Toaster } from "react-hot-toast";
import LoginModal from "@components/ui/Modal/LoginModal";
import getCurrentUser from "@src/actions/getCurrentUser";
import { Inter } from "next/font/google";
import { RootWrapper } from "@components/components";

export const metadata = {
  title: "Airbnb Clone",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <RootWrapper currentUser={currentUser}>{children}</RootWrapper>
      </body>
    </html>
  );
}
