import { Navbar } from "@/components/ui";
import "./globals.css";

export const metadata = {
  title: "Airbnb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
